# ================================================================================
# MNIST FedAvg Centralized Experiment with TorchDist Communication
# Complete configuration for MNIST experiments with FedAvg algorithm.
# Uses centralized topology with 3 clients and TorchDist communication.
# Runs for 3 global rounds with 4 local epochs per round.
# ================================================================================

defaults:
  - base # Base framework configuration
  - override topology: centralized # see ./conf/topology/centralized.yaml
  - override algorithm: synchronousDP # see ./conf/algorithm/synchronousDP.yaml
  - override model: resnet18 # see ./conf/model/simple_cnn.yaml
  - override datamodule: cifar10 # see ./conf/datamodule/mnist.yaml
  - _self_ # Everything below is merged on top of the above defaults

# ─────────────────────────────────── Topology Overrides
topology:
  num_clients: 3
  local_comm:
    _target_: src.omnifed.communicator.GrpcCommunicator
    # master_addr: 127.0.0.1 # Default
    master_port: 50051
    compressor:
        _target_: src.omnifed.communicator.compression.sparsification.TopKCompression
        compress_ratio: 0.01

  overrides:
    0: # Rank 0 (server) - disable training by setting train dataloader to null
      datamodule:
        train: null

# ─────────────────────────────────── Algorithm Overrides
algorithm:
  local_lr: 0.005
  max_epochs_per_round: 3

# ─────────────────────────────────── Model Overrides
model:
  # backbone:
  #   in_channels: 1 # MNIST grayscale
  # head:
  num_classes: 10 # MNIST digits

# ─────────────────────────────────── DataModule Overrides
datamodule:
  train:
    batch_size: 128
  eval:
    batch_size: 128

# ─────────────────────────────────── Engine Parameters
global_rounds: 2 # see ./conf/base.yaml for all options
