# PI centralized — sync grad + Top-K over gRPC (CIFAR-10, ResNet-18).

defaults:
  - test_pi_centralized_sync_grad_cifar10_resnet18_grpc
  - _self_

topology:
  local_comm:
    compressor:
      _target_: src.omnifed.communicator.compression.sparsification.TopKCompression
      device: cpu
      compress_ratio: 0.01
